/test addworld("PrairieMOO", "tiny.moo", "Trixie.local", "7777")
/test addworld("SerenityMUSH", "tiny.mush", "192.95.60.225", "2020")
/test addworld("tt2", "tiny.mush", "tales.mushserver.com", "6250")
/test addworld("Serenity", "tiny.mush", "192.95.60.225", "2020")
/test addworld("Miriani", "tiny.moo", "toastsoft.net", "1234")
/test addworld("Penultimate", "tiny.mush", "penultimatemush.com", "9500")
/test addworld("LambdaMOO", "tiny.moo", "lambda.moo.mud.org", "8888")
/test addworld("FurryMUCK", "tiny.muck", "furrymuck.com", "8888")
